logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka        
server:
  port: 9800


  
spring:
  application:
    name: app-dongl-spike
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 1
        max-wait: -1ms
        max-active: 8
        min-idle: 1

###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/shopmall?useUnicode=true&characterEncoding=UTF-8

  rabbitmq:
  ####连接地址
    host: 192.168.1.107
   ####端口号
    port: 5672
   ####账号
    username: root
   ####密码
    password: 123456
   ### 地址
    virtual-host: admin_host
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true