
server:
  port: 8050

#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-portal-pay
    cloud:
      loadbalancer:
        retry:
          enabled: true
    redis:
      host: 192.168.1.107
      port: 6379
      password: 123456
      jedis:
        pool:
        # 连接池中的最大空闲连接
          max-idle: 100
          # 连接池中的最小空闲连接
          min-idle: 1
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 1000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

# 添加 XXL-SSO 配置
xxl-sso:
  excluded:
    paths:
xxl:
  sso:
#    server: http://xxlssoserver.com:8080/xxl-sso-server
    server: http://127.0.0.1:8080/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://192.168.1.107:6379


