
###服务启动端口号
server:
  port: 8800
###服务名称(服务注册到eureka名称)  
#spring:
#    application:
#        name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


  
spring:
  application:
    name:  app-dongl-integral
#  zipkin:
#      base-url: http://127.0.0.1:9411/
#      ###全部采集
#  sleuth:
#     sampler:
#      probability: 1.0
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 1
        max-wait: -1ms
        max-active: 8
        min-idle: 1


###数据库相关连接      
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/shopmall?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
  ####连接地址
    host: 192.168.1.107
   ####端口号   
    port: 5672
   ####账号 
    username: root
   ####密码  
    password: 123456
   ### 地址
    virtual-host: admin_host
    listener:
      simple:
        retry:
        ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
         ####最大重试次数
          max-attempts: 5
        ####重试间隔时间
          initial-interval: 1000ms
        ####开启手动ack  
        acknowledge-mode: manual 
        default-requeue-rejected: false
####打印MyBatias日志    
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
   com.mayikt.member.mapper: DEBUG
   

   
