

server:
  port: 80

#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-dongl-portal-web

    # Redis
    redis:
      host: 192.168.1.107
      port: 6379
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

###服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#           defaultZone: http://localhost:8100/eureka


#xxl-sso:
#  excluded:
#    paths:
#xxl:
#  sso:
#    server: http://xxlssoserver.com:8080/xxl-sso-server
#    logout:
#      path: /logout
#    redis:
#      address: redis://127.0.0.1:6379


