logging:
    config: classpath:logback.xml
server:
    port: 8082
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://127.0.0.1:8080/xxl-job-admin
        executor:
            appname: xxl-job-executor-sample
            ip: '127.0.0.1'
            logpath: /data/applogs/xxl-job/jobhandler
            logretentiondays: 30
            port: 9999


## 访问地址: http://127.0.0.1:8080/xxl-job-admin