###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    name:  app-dongl-goods
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 1
        max-wait: -1ms
        max-active: 8
        min-idle: 1
###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###  数据库的名称为
    url: jdbc:mysql://47.94.10.48:3306/goods?useUnicode=true&characterEncoding=UTF-8
  data:
    elasticsearch:
    ####集群名称 和配置文件中的 cluster_name 保持一致
     cluster-name: elasticsearch-cluster
    ####  9300端口： ES节点之间通讯使用
     cluster-nodes: 192.168.1.107:9300
  kafka:
    bootstrap-servers: 192.168.1.120:9092

## 该模块需要启动elk ,Zookeeper ，kafka服务器，同时需要启动 eureka服务。