#logging:
#  level:
#    org.springframework.web: INFO
#    com.github.binarywang.demo.wx.mp: DEBUG
#    me.chanjar.weixin: DEBUG
#wx:
#  mp:
#    configs:
#      - appId: wx3caf9762ead9e312                   # （一个公众号的appid）
#        secret: b59ddea9767c77a220af4e4f0d4e57d6    # 公众号的appsecret）
#        token: dongl                                #（接口配置里的Token值）
#
#dongl:
#  weixin:
#    template :
#      code:
#        message: 欢迎您关注 “姚广玉酷跑测试公众号”，点击网址：<a href="http://dongl.natapp1.cc/getApp"> 领取100元红包 ！ </a>，手慢则无。
#        message: 您的注册码为:templateMsg，请关注<a href="http://dongl.natapp1.cc/getApp">姚广玉酷跑测试公众号</a>，并有机会领取100元红包 ！，期待你的加入，感谢！
#    default:
#      template :
#            code:
#              message: 您的消息，已成功投送到火星之巅，我们将及时回复您。


spring:
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    pool:
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


#        aesKey: 111 （接口配置里的EncodingAESKey值）
#      - appId: 2222 （另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111

#  通过内外穿透 映射的 地址：  http://dongl.natapp1.cc
#server:
#  port: 8400
