### 服务启动端口
server:
  port: 8300

### 服务名称（服务注册到eureka 的名称）
spring:
  application:
    name: app-member

### 服务注册到 eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka

### 微信端口号：8200 8201 8202   会员端口号：8300 83001 83002   有序编号为了后续集群。
