
spring:
  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
    pool:
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

###数据库相关连接
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/shopmall
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.dongl.member.mapper: DEBUG



#        aesKey: 111 （接口配置里的EncodingAESKey值）
#      - appId: 2222 （另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111

#  通过内外穿透 映射的 地址：  http://dongl.natapp1.cc
#server:
#  port: 8400
